import os

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")

MIN_PROBABILITY = 75
VOLUME_FILTER = 40_000_000

TIMEFRAMES = ["15m", "1h"]

MEXC_BASE_URL = "https://contract.mexc.com"
