TELEGRAM_BOT_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"

# Blofin API keys
API_KEY = "YOUR_API_KEY"
API_SECRET = "YOUR_API_SECRET"
API_PASSWORD = "YOUR_API_PASSWORD"     # Needed for Blofin

EXCHANGE_ID = "blofin"

# Grid settings
GRID_INTERVAL = 5   # seconds
ORDER_SIZE_USDT = 10

# IMPORTANT: Blofin symbols (NO SLASH)
PAIRS = ["BTCUSDT", "SUIUSDT"]

