import os

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")

BITGET_API_KEY = os.getenv("BITGET_API_KEY")
BITGET_API_SECRET = os.getenv("BITGET_API_SECRET")
BITGET_PASSPHRASE = os.getenv("BITGET_PASSPHRASE")

PAIRS = ["BTC/USDT", "SUI/USDT"]

MIN_ORDER = {
    "BTC/USDT": 9.5,
    "SUI/USDT": 5.5,
}

DEFAULT_LEVERAGE = 5

GRID_LOOP_SECONDS = 15
